arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - joint_0
     - joint_1
     - joint_2
     - joint_3
     - joint_4
     - joint_5
  gains:
      joint_0: {p: 100, i: 0.01, d: 1}
      joint_1: {p: 100, i: 0.01, d: 1}
      joint_2: {p: 100, i: 0.01, d: 1}
      joint_3: {p: 100, i: 0.01, d: 1}
      joint_4: {p: 100, i: 0.01, d: 1}
      joint_5: {p: 100, i: 0.01, d: 1}
  constraints:
      goal_time: 10.0

  state_publish_rate: 50
  action_monitor_rate: 30
  stop_trajectory_duration: 0




