#generic_hw_control_loop:
#  loop_hz: 300
#  cycle_time_error_threshold: 0.01
#
# Settings for ros_control hardware interface
#hardware_interface:
#   joints:
#      - joint_0
#      - joint_1
#      - joint_2
#      - joint_3
#      - joint_4
#      - joint_5
#      - joint_finger1
#      - joint_finger2
#      - front_left_wheel_joint
#      - front_right_wheel_joint
#      - back_left_wheel_joint
#      - back_right_wheel_joint
#   sim_control_mode: 0 # 0: position, 1: velocity

kinect_controller:
  type: position_controllers/JointPositionController
  joint: camera_rgb_joint


arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - joint_0
     - joint_1
     - joint_2
     - joint_3
     - joint_4
     - joint_5
  gains:
      joint_0: {p: 100, i: 0.01, d: 1}
      joint_1: {p: 100, i: 0.01, d: 1}
      joint_2: {p: 100, i: 0.01, d: 1}
      joint_3: {p: 100, i: 0.01, d: 1}
      joint_4: {p: 100, i: 0.01, d: 1}
      joint_5: {p: 100, i: 0.01, d: 1}
  constraints:
      goal_time: 10.0

  state_publish_rate: 50
  action_monitor_rate: 30
  stop_trajectory_duration: 0

gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
     - joint_finger1
     - joint_finger2
  gains:
      joint_finger1: {p: 100, i: 1, d: 10, i_clamp: 1.0}
      joint_finger2: {p: 100, i: 1, d: 10, i_clamp: 1.0}
  constraints:
      goal_time: 3.0

      joint_finger1: {goal: 0.02}
      joint_finger2: {goal: 0.02}

  
  state_publish_rate:  50
  action_monitor_rate: 30
  stop_trajectory_duration: 0


