<?xml version="1.0" ?>

<robot name="lynx_rover" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <!--xacro:include filename="$(find lynxbot_description)/urdf/common_properties.urdf.xacro" /-->
    <xacro:include filename="$(find lynxbot_description)/urdf/macros/inertia_macros.urdf.xacro" />
  <xacro:macro name="arm_link" params="link_name length 
    radius origin_xyz origin_rpy color_name color mass">

    <link name="${link_name}">
  

      <xacro:cylinder_inertial radius="${radius}" length="${length}" mass="${mass}">
        <origin xyz="${origin_xyz}" rpy="${origin_rpy}"/>
      </xacro:cylinder_inertial>
      <visual>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
        <origin xyz="${origin_xyz}" rpy="${origin_rpy}"/>
        <material name="${color_name}">
          <color rgba="${color}"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${length*0.5}" radius="${radius*0.5}"/>
        </geometry>
        <origin xyz="${origin_xyz}" rpy="${origin_rpy}"/>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="arm_joint" params="joint_name type parent child 
    origin_xyz origin_rpy axis_xyz axis_rpy lower_limit upper_limit">

    <joint type="${type}" name="${joint_name}">
    <origin xyz="${origin_xyz}" rpy="${origin_rpy}"/>
    <child link="${child}"/>
    <parent link="${parent}"/>
    <axis xyz="${axis_xyz}" rpy="${axis_rpy}"/>
    <limit effort="100.0" velocity="1.0" lower="${lower_limit}" upper="${upper_limit}"/>
    <joint_properties damping="0.0" friction="10.0"/>
    <!--safety_controller k_velocity="10.0" k_position="15.0" soft_lower_limit="${lower_limit}" soft_upper_limit="${upper_limit}" /-->
  </joint>
  </xacro:macro>


  <xacro:macro name="ee_link" params="link_name size_x size_y size_z 
  origin_xyz origin_rpy color_name color mass">

    <link name="${link_name}">
  
      <xacro:box_inertial x="${size_x}" y="${size_y}" z="${size_z}" m="${mass}">
        <origin xyz="${origin_xyz}" rpy="${origin_rpy}"/>
      </xacro:box_inertial>

      <visual>
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}"/>
        </geometry>
        <origin xyz="${origin_xyz}" rpy="${origin_rpy}"/>
        <material name="${color_name}">
          <color rgba="${color}"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${size_x*0.5} ${size_y*0.5} ${size_z*0.5}"/>
        </geometry>
        <origin xyz="${origin_xyz}" rpy="${origin_rpy}"/>
      </collision>
    </link>
  </xacro:macro>

</robot>
