port: /dev/ydlidar 
baudrate: 115200
frame_id: laser_link
low_exposure: false
resolution_fixed: true
auto_reconnect: true
reversion: false
angle_min: -180
angle_max: 180
range_min: 0.25
range_max: 6.0
ignore_array: "" 
samp_rate: 9
frequency: 6
