global_frame: map
robot_base_frame: robot_footprint
update_frequency: 20
publish_frequency: 10
width: 20.0
height: 20.0
resolution: 0.05
static_map: true
track_unknown_space: true
rolling_window: false
plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: obstacles_laser,         type: "costmap_2d::VoxelLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}

