global_frame: odom
robot_base_frame: robot_footprint
update_frequency: 20
publish_frequency: 5
width: 5
height: 5
resolution: 0.02
#static_map: false
rolling_window: true

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}

