generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
   joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_finger1
      - joint_finger2
      - front_left_wheel_joint
      - front_right_wheel_joint
      - back_left_wheel_joint
      - back_right_wheel_joint
   sim_control_mode: 0 # 0: position, 1: velocity



joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
     - joint_0
     - joint_1
     - joint_2
     - joint_3
     - joint_4
     - joint_5
  gains:
      joint_0: {p: 10, i: 0.1, d: 0.01, i_clamp: 1}
      joint_1: {p: 10, i: 0.1, d: 0.01, i_clamp: 1}
      joint_2: {p: 10, i: 0.1, d: 0.01, i_clamp: 1}
      joint_3: {p: 10, i: 0.1, d: 0.01, i_clamp: 1}
      joint_4: {p: 10, i: 0.1, d: 0.01, i_clamp: 1}
      joint_5: {p: 10, i: 0.1, d: 0.01, i_clamp: 1}
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_0: {trajectory: 0.1, goal: 0.1}
      joint_1: {trajectory: 0.1, goal: 0.1}
      joint_2: {trajectory: 0.1, goal: 0.1}
      joint_3: {trajectory: 0.1, goal: 0.1}
      joint_4: {trajectory: 0.1, goal: 0.1}
      joint_5: {trajectory: 0.1, goal: 0.1}

gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
     - joint_finger1
     - joint_finger2
  gains:
      joint_finger1: {p: 10, i: 0.1, d: 0.01, i_clamp: 1}
      joint_finger2: {p: 10, i: 0.1, d: 0.01, i_clamp: 1}
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_finger1: {trajectory: 1.1, goal: 0.1}
      joint_finger2: {trajectory: 1.1, goal: 0.1}

  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10


